package xdt.quickpay.qianlong.model;

import java.util.Date;

public class Merchant {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_merchant.mchnt_id
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	private String mchntId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_merchant.org_id
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	private String orgId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_merchant.cbzid
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	private String cbzid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_merchant.code
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_merchant.account
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	private String account;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_merchant.password
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_merchant.mchnt_name
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	private String mchntName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_merchant.real_name
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	private String realName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_merchant.card_type
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	private String cardType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_merchant.card_no
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	private String cardNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_merchant.cert_type
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	private String certType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_merchant.cert_no
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	private String certNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_merchant.mobile
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	private String mobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_merchant.city_cd
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	private String cityCd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_merchant.pms_bank_no
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	private String pmsBankNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_merchant.cert_correct
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	private String certCorrect;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_merchant.cert_opposite
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	private String certOpposite;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_merchant.cert_meet
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	private String certMeet;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_merchant.card_correct
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	private String cardCorrect;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_merchant.card_opposite
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	private String cardOpposite;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_merchant.private_key
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	private String privateKey;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_merchant.regist_dt
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	private String registDt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_merchant.commis_rate
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	private Double commisRate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_merchant.account_st
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	private Integer accountSt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_merchant.fqr_open_st
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	private Integer fqrOpenSt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_merchant.fee_rate
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	private Double feeRate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_merchant.ocp_open_st
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	private Integer ocpOpenSt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_merchant.row_crt_ts
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	private Date rowCrtTs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_merchant.row_crt_usr
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	private String rowCrtUsr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_merchant.row_upd_ts
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	private Date rowUpdTs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_merchant.row_upd_usr
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	private String rowUpdUsr;
	
	private String result;
	
	private String postdata;
	
	private String signature;
	
	private String agentNumber;
	
	public String getSignature() {
		return signature;
	}

	public void setSignature(String signature) {
		this.signature = signature;
	}
	
	public String getResult() {
		return result;
	}
	public void setResult(String result) {
		this.result = result;
	}
	public String getPostdata() {
		return postdata;
	}
	public void setPostdata(String postdata) {
		this.postdata = postdata;
	}
	public String getAgentNumber() {
		return agentNumber;
	}

	public void setAgentNumber(String agentNumber) {
		this.agentNumber = agentNumber;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_merchant.mchnt_id
	 * @return  the value of t_merchant.mchnt_id
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	public String getMchntId() {
		return mchntId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_merchant.mchnt_id
	 * @param mchntId  the value for t_merchant.mchnt_id
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	public void setMchntId(String mchntId) {
		this.mchntId = mchntId == null ? null : mchntId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_merchant.org_id
	 * @return  the value of t_merchant.org_id
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	public String getOrgId() {
		return orgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_merchant.org_id
	 * @param orgId  the value for t_merchant.org_id
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	public void setOrgId(String orgId) {
		this.orgId = orgId == null ? null : orgId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_merchant.cbzid
	 * @return  the value of t_merchant.cbzid
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	public String getCbzid() {
		return cbzid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_merchant.cbzid
	 * @param cbzid  the value for t_merchant.cbzid
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	public void setCbzid(String cbzid) {
		this.cbzid = cbzid == null ? null : cbzid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_merchant.code
	 * @return  the value of t_merchant.code
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_merchant.code
	 * @param code  the value for t_merchant.code
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	public void setCode(String code) {
		this.code = code == null ? null : code.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_merchant.account
	 * @return  the value of t_merchant.account
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	public String getAccount() {
		return account;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_merchant.account
	 * @param account  the value for t_merchant.account
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	public void setAccount(String account) {
		this.account = account == null ? null : account.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_merchant.password
	 * @return  the value of t_merchant.password
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_merchant.password
	 * @param password  the value for t_merchant.password
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_merchant.mchnt_name
	 * @return  the value of t_merchant.mchnt_name
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	public String getMchntName() {
		return mchntName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_merchant.mchnt_name
	 * @param mchntName  the value for t_merchant.mchnt_name
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	public void setMchntName(String mchntName) {
		this.mchntName = mchntName == null ? null : mchntName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_merchant.real_name
	 * @return  the value of t_merchant.real_name
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	public String getRealName() {
		return realName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_merchant.real_name
	 * @param realName  the value for t_merchant.real_name
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	public void setRealName(String realName) {
		this.realName = realName == null ? null : realName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_merchant.card_type
	 * @return  the value of t_merchant.card_type
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	public String getCardType() {
		return cardType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_merchant.card_type
	 * @param cardType  the value for t_merchant.card_type
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	public void setCardType(String cardType) {
		this.cardType = cardType == null ? null : cardType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_merchant.card_no
	 * @return  the value of t_merchant.card_no
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	public String getCardNo() {
		return cardNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_merchant.card_no
	 * @param cardNo  the value for t_merchant.card_no
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	public void setCardNo(String cardNo) {
		this.cardNo = cardNo == null ? null : cardNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_merchant.cert_type
	 * @return  the value of t_merchant.cert_type
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	public String getCertType() {
		return certType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_merchant.cert_type
	 * @param certType  the value for t_merchant.cert_type
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	public void setCertType(String certType) {
		this.certType = certType == null ? null : certType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_merchant.cert_no
	 * @return  the value of t_merchant.cert_no
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	public String getCertNo() {
		return certNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_merchant.cert_no
	 * @param certNo  the value for t_merchant.cert_no
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	public void setCertNo(String certNo) {
		this.certNo = certNo == null ? null : certNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_merchant.mobile
	 * @return  the value of t_merchant.mobile
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_merchant.mobile
	 * @param mobile  the value for t_merchant.mobile
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile == null ? null : mobile.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_merchant.city_cd
	 * @return  the value of t_merchant.city_cd
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	public String getCityCd() {
		return cityCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_merchant.city_cd
	 * @param cityCd  the value for t_merchant.city_cd
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	public void setCityCd(String cityCd) {
		this.cityCd = cityCd == null ? null : cityCd.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_merchant.pms_bank_no
	 * @return  the value of t_merchant.pms_bank_no
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	public String getPmsBankNo() {
		return pmsBankNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_merchant.pms_bank_no
	 * @param pmsBankNo  the value for t_merchant.pms_bank_no
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	public void setPmsBankNo(String pmsBankNo) {
		this.pmsBankNo = pmsBankNo == null ? null : pmsBankNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_merchant.cert_correct
	 * @return  the value of t_merchant.cert_correct
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	public String getCertCorrect() {
		return certCorrect;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_merchant.cert_correct
	 * @param certCorrect  the value for t_merchant.cert_correct
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	public void setCertCorrect(String certCorrect) {
		this.certCorrect = certCorrect == null ? null : certCorrect.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_merchant.cert_opposite
	 * @return  the value of t_merchant.cert_opposite
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	public String getCertOpposite() {
		return certOpposite;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_merchant.cert_opposite
	 * @param certOpposite  the value for t_merchant.cert_opposite
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	public void setCertOpposite(String certOpposite) {
		this.certOpposite = certOpposite == null ? null : certOpposite.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_merchant.cert_meet
	 * @return  the value of t_merchant.cert_meet
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	public String getCertMeet() {
		return certMeet;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_merchant.cert_meet
	 * @param certMeet  the value for t_merchant.cert_meet
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	public void setCertMeet(String certMeet) {
		this.certMeet = certMeet == null ? null : certMeet.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_merchant.card_correct
	 * @return  the value of t_merchant.card_correct
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	public String getCardCorrect() {
		return cardCorrect;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_merchant.card_correct
	 * @param cardCorrect  the value for t_merchant.card_correct
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	public void setCardCorrect(String cardCorrect) {
		this.cardCorrect = cardCorrect == null ? null : cardCorrect.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_merchant.card_opposite
	 * @return  the value of t_merchant.card_opposite
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	public String getCardOpposite() {
		return cardOpposite;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_merchant.card_opposite
	 * @param cardOpposite  the value for t_merchant.card_opposite
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	public void setCardOpposite(String cardOpposite) {
		this.cardOpposite = cardOpposite == null ? null : cardOpposite.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_merchant.private_key
	 * @return  the value of t_merchant.private_key
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	public String getPrivateKey() {
		return privateKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_merchant.private_key
	 * @param privateKey  the value for t_merchant.private_key
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	public void setPrivateKey(String privateKey) {
		this.privateKey = privateKey == null ? null : privateKey.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_merchant.regist_dt
	 * @return  the value of t_merchant.regist_dt
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	public String getRegistDt() {
		return registDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_merchant.regist_dt
	 * @param registDt  the value for t_merchant.regist_dt
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	public void setRegistDt(String registDt) {
		this.registDt = registDt == null ? null : registDt.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_merchant.commis_rate
	 * @return  the value of t_merchant.commis_rate
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	public Double getCommisRate() {
		return commisRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_merchant.commis_rate
	 * @param commisRate  the value for t_merchant.commis_rate
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	public void setCommisRate(Double commisRate) {
		this.commisRate = commisRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_merchant.account_st
	 * @return  the value of t_merchant.account_st
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	public Integer getAccountSt() {
		return accountSt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_merchant.account_st
	 * @param accountSt  the value for t_merchant.account_st
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	public void setAccountSt(Integer accountSt) {
		this.accountSt = accountSt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_merchant.fqr_open_st
	 * @return  the value of t_merchant.fqr_open_st
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	public Integer getFqrOpenSt() {
		return fqrOpenSt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_merchant.fqr_open_st
	 * @param fqrOpenSt  the value for t_merchant.fqr_open_st
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	public void setFqrOpenSt(Integer fqrOpenSt) {
		this.fqrOpenSt = fqrOpenSt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_merchant.fee_rate
	 * @return  the value of t_merchant.fee_rate
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	public Double getFeeRate() {
		return feeRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_merchant.fee_rate
	 * @param feeRate  the value for t_merchant.fee_rate
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	public void setFeeRate(Double feeRate) {
		this.feeRate = feeRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_merchant.ocp_open_st
	 * @return  the value of t_merchant.ocp_open_st
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	public Integer getOcpOpenSt() {
		return ocpOpenSt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_merchant.ocp_open_st
	 * @param ocpOpenSt  the value for t_merchant.ocp_open_st
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	public void setOcpOpenSt(Integer ocpOpenSt) {
		this.ocpOpenSt = ocpOpenSt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_merchant.row_crt_ts
	 * @return  the value of t_merchant.row_crt_ts
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	public Date getRowCrtTs() {
		return rowCrtTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_merchant.row_crt_ts
	 * @param rowCrtTs  the value for t_merchant.row_crt_ts
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	public void setRowCrtTs(Date rowCrtTs) {
		this.rowCrtTs = rowCrtTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_merchant.row_crt_usr
	 * @return  the value of t_merchant.row_crt_usr
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	public String getRowCrtUsr() {
		return rowCrtUsr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_merchant.row_crt_usr
	 * @param rowCrtUsr  the value for t_merchant.row_crt_usr
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	public void setRowCrtUsr(String rowCrtUsr) {
		this.rowCrtUsr = rowCrtUsr == null ? null : rowCrtUsr.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_merchant.row_upd_ts
	 * @return  the value of t_merchant.row_upd_ts
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	public Date getRowUpdTs() {
		return rowUpdTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_merchant.row_upd_ts
	 * @param rowUpdTs  the value for t_merchant.row_upd_ts
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	public void setRowUpdTs(Date rowUpdTs) {
		this.rowUpdTs = rowUpdTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_merchant.row_upd_usr
	 * @return  the value of t_merchant.row_upd_usr
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	public String getRowUpdUsr() {
		return rowUpdUsr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_merchant.row_upd_usr
	 * @param rowUpdUsr  the value for t_merchant.row_upd_usr
	 * @mbg.generated  Mon Oct 24 18:48:31 CST 2016
	 */
	public void setRowUpdUsr(String rowUpdUsr) {
		this.rowUpdUsr = rowUpdUsr == null ? null : rowUpdUsr.trim();
	}

	@Override
	public String toString() {
		return "Merchant [mchntId=" + mchntId + ", orgId=" + orgId + ", cbzid="
				+ cbzid + ", code=" + code + ", account=" + account
				+ ", password=" + password + ", mchntName=" + mchntName
				+ ", realName=" + realName + ", cardType=" + cardType
				+ ", cardNo=" + cardNo + ", certType=" + certType + ", certNo="
				+ certNo + ", mobile=" + mobile + ", cityCd=" + cityCd
				+ ", pmsBankNo=" + pmsBankNo + ", certCorrect=" + certCorrect
				+ ", certOpposite=" + certOpposite + ", certMeet=" + certMeet
				+ ", cardCorrect=" + cardCorrect + ", cardOpposite="
				+ cardOpposite + ", privateKey=" + privateKey + ", registDt="
				+ registDt + ", commisRate=" + commisRate + ", accountSt="
				+ accountSt + ", fqrOpenSt=" + fqrOpenSt + ", feeRate="
				+ feeRate + ", ocpOpenSt=" + ocpOpenSt + ", rowCrtTs="
				+ rowCrtTs + ", rowCrtUsr=" + rowCrtUsr + ", rowUpdTs="
				+ rowUpdTs + ", rowUpdUsr=" + rowUpdUsr + ", result=" + result
				+ ", postdata=" + postdata + ", signature=" + signature
				+ ", agentNumber=" + agentNumber + "]";
	}
   
	
	
}