package xdt.quickpay.qianlong.model;

import java.util.Date;

public class Order {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.order_no
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	private String orderNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.order_dt
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	private String orderDt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.source
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	private Integer source;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.org_id
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	private String orgId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.org_order_no
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	private String orgOrderNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.account
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	private String account;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.appid
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	private String appid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.pay_channel_id
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	private String payChannelId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.amount
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	private Integer amount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.settle_amt
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	private Integer settleAmt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.client_ip
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	private String clientIp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.currency
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	private String currency;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.subject
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	private String subject;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.body
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	private String body;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.time_expire
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	private Date timeExpire;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.description
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.created
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	private Date created;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.time_paid
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	private Date timePaid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.bank_type
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	private String bankType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.pay_st
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	private Integer paySt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.refund_st
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	private Integer refundSt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.refunded_amt
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	private Integer refundedAmt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.check_st
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	private Integer checkSt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.fee
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	private Integer fee;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.chnl_fee
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	private Integer chnlFee;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.tran_tp
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	private Integer tranTp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.order_tp
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	private Integer orderTp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.settle_st
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	private Integer settleSt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.rut_id
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	private String rutId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.qrcode_url
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	private String qrcodeUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.bank_rsp_cd
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	private String bankRspCd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.bank_rsp_desc
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	private String bankRspDesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.bank_transaction_id
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	private String bankTransactionId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.notify_url
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	private String notifyUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.payfor_notify_url
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	private String payforNotifyUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.callback_url
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	private String callbackUrl;
	/**notifyUrl
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.notify_cnt
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	private Integer notifyCnt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.notify_st
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	private Integer notifySt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.open_id
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	private String openId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.extra
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	private String extra;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.country_id
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	private String countryId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.area_id
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	private String areaId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.region_id
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	private String regionId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.city_id
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	private String cityId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.county_id
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	private String countyId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.reserved3
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	private Integer reserved3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.reserved2
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	private Integer reserved2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.reserved1
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	private Integer reserved1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.modified
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	private Date modified;
	
	private String merchantId;
	
	private String signature;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.order_no
	 * @return  the value of t_order.order_no
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public String getOrderNo() {
		return orderNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.order_no
	 * @param orderNo  the value for t_order.order_no
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public void setOrderNo(String orderNo) {
		this.orderNo = orderNo == null ? null : orderNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.order_dt
	 * @return  the value of t_order.order_dt
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public String getOrderDt() {
		return orderDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.order_dt
	 * @param orderDt  the value for t_order.order_dt
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public void setOrderDt(String orderDt) {
		this.orderDt = orderDt == null ? null : orderDt.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.source
	 * @return  the value of t_order.source
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public Integer getSource() {
		return source;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.source
	 * @param source  the value for t_order.source
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public void setSource(Integer source) {
		this.source = source;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.org_id
	 * @return  the value of t_order.org_id
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public String getOrgId() {
		return orgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.org_id
	 * @param orgId  the value for t_order.org_id
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public void setOrgId(String orgId) {
		this.orgId = orgId == null ? null : orgId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.org_order_no
	 * @return  the value of t_order.org_order_no
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public String getOrgOrderNo() {
		return orgOrderNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.org_order_no
	 * @param orgOrderNo  the value for t_order.org_order_no
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public void setOrgOrderNo(String orgOrderNo) {
		this.orgOrderNo = orgOrderNo == null ? null : orgOrderNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.account
	 * @return  the value of t_order.account
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public String getAccount() {
		return account;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.account
	 * @param account  the value for t_order.account
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public void setAccount(String account) {
		this.account = account == null ? null : account.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.appid
	 * @return  the value of t_order.appid
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public String getAppid() {
		return appid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.appid
	 * @param appid  the value for t_order.appid
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public void setAppid(String appid) {
		this.appid = appid == null ? null : appid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.pay_channel_id
	 * @return  the value of t_order.pay_channel_id
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public String getPayChannelId() {
		return payChannelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.pay_channel_id
	 * @param payChannelId  the value for t_order.pay_channel_id
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public void setPayChannelId(String payChannelId) {
		this.payChannelId = payChannelId == null ? null : payChannelId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.amount
	 * @return  the value of t_order.amount
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public Integer getAmount() {
		return amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.amount
	 * @param amount  the value for t_order.amount
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public void setAmount(Integer amount) {
		this.amount = amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.settle_amt
	 * @return  the value of t_order.settle_amt
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public Integer getSettleAmt() {
		return settleAmt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.settle_amt
	 * @param settleAmt  the value for t_order.settle_amt
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public void setSettleAmt(Integer settleAmt) {
		this.settleAmt = settleAmt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.client_ip
	 * @return  the value of t_order.client_ip
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public String getClientIp() {
		return clientIp;
	}





	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.client_ip
	 * @param clientIp  the value for t_order.client_ip
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public void setClientIp(String clientIp) {
		this.clientIp = clientIp == null ? null : clientIp.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.currency
	 * @return  the value of t_order.currency
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public String getCurrency() {
		return currency;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.currency
	 * @param currency  the value for t_order.currency
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public void setCurrency(String currency) {
		this.currency = currency == null ? null : currency.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.subject
	 * @return  the value of t_order.subject
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public String getSubject() {
		return subject;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.subject
	 * @param subject  the value for t_order.subject
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public void setSubject(String subject) {
		this.subject = subject == null ? null : subject.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.body
	 * @return  the value of t_order.body
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public String getBody() {
		return body;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.body
	 * @param body  the value for t_order.body
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public void setBody(String body) {
		this.body = body == null ? null : body.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.time_expire
	 * @return  the value of t_order.time_expire
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public Date getTimeExpire() {
		return timeExpire;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.time_expire
	 * @param timeExpire  the value for t_order.time_expire
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public void setTimeExpire(Date timeExpire) {
		this.timeExpire = timeExpire;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.description
	 * @return  the value of t_order.description
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.description
	 * @param description  the value for t_order.description
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.created
	 * @return  the value of t_order.created
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public Date getCreated() {
		return created;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.created
	 * @param created  the value for t_order.created
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public void setCreated(Date created) {
		this.created = created;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.time_paid
	 * @return  the value of t_order.time_paid
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public Date getTimePaid() {
		return timePaid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.time_paid
	 * @param timePaid  the value for t_order.time_paid
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public void setTimePaid(Date timePaid) {
		this.timePaid = timePaid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.bank_type
	 * @return  the value of t_order.bank_type
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public String getBankType() {
		return bankType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.bank_type
	 * @param bankType  the value for t_order.bank_type
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public void setBankType(String bankType) {
		this.bankType = bankType == null ? null : bankType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.pay_st
	 * @return  the value of t_order.pay_st
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public Integer getPaySt() {
		return paySt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.pay_st
	 * @param paySt  the value for t_order.pay_st
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public void setPaySt(Integer paySt) {
		this.paySt = paySt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.refund_st
	 * @return  the value of t_order.refund_st
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public Integer getRefundSt() {
		return refundSt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.refund_st
	 * @param refundSt  the value for t_order.refund_st
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public void setRefundSt(Integer refundSt) {
		this.refundSt = refundSt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.refunded_amt
	 * @return  the value of t_order.refunded_amt
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public Integer getRefundedAmt() {
		return refundedAmt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.refunded_amt
	 * @param refundedAmt  the value for t_order.refunded_amt
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public void setRefundedAmt(Integer refundedAmt) {
		this.refundedAmt = refundedAmt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.check_st
	 * @return  the value of t_order.check_st
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public Integer getCheckSt() {
		return checkSt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.check_st
	 * @param checkSt  the value for t_order.check_st
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public void setCheckSt(Integer checkSt) {
		this.checkSt = checkSt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.fee
	 * @return  the value of t_order.fee
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public Integer getFee() {
		return fee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.fee
	 * @param fee  the value for t_order.fee
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public void setFee(Integer fee) {
		this.fee = fee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.chnl_fee
	 * @return  the value of t_order.chnl_fee
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public Integer getChnlFee() {
		return chnlFee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.chnl_fee
	 * @param chnlFee  the value for t_order.chnl_fee
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public void setChnlFee(Integer chnlFee) {
		this.chnlFee = chnlFee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.tran_tp
	 * @return  the value of t_order.tran_tp
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public Integer getTranTp() {
		return tranTp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.tran_tp
	 * @param tranTp  the value for t_order.tran_tp
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public void setTranTp(Integer tranTp) {
		this.tranTp = tranTp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.order_tp
	 * @return  the value of t_order.order_tp
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public Integer getOrderTp() {
		return orderTp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.order_tp
	 * @param orderTp  the value for t_order.order_tp
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public void setOrderTp(Integer orderTp) {
		this.orderTp = orderTp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.settle_st
	 * @return  the value of t_order.settle_st
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public Integer getSettleSt() {
		return settleSt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.settle_st
	 * @param settleSt  the value for t_order.settle_st
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public void setSettleSt(Integer settleSt) {
		this.settleSt = settleSt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.rut_id
	 * @return  the value of t_order.rut_id
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public String getRutId() {
		return rutId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.rut_id
	 * @param rutId  the value for t_order.rut_id
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public void setRutId(String rutId) {
		this.rutId = rutId == null ? null : rutId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.qrcode_url
	 * @return  the value of t_order.qrcode_url
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public String getQrcodeUrl() {
		return qrcodeUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.qrcode_url
	 * @param qrcodeUrl  the value for t_order.qrcode_url
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public void setQrcodeUrl(String qrcodeUrl) {
		this.qrcodeUrl = qrcodeUrl == null ? null : qrcodeUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.bank_rsp_cd
	 * @return  the value of t_order.bank_rsp_cd
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public String getBankRspCd() {
		return bankRspCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.bank_rsp_cd
	 * @param bankRspCd  the value for t_order.bank_rsp_cd
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public void setBankRspCd(String bankRspCd) {
		this.bankRspCd = bankRspCd == null ? null : bankRspCd.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.bank_rsp_desc
	 * @return  the value of t_order.bank_rsp_desc
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public String getBankRspDesc() {
		return bankRspDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.bank_rsp_desc
	 * @param bankRspDesc  the value for t_order.bank_rsp_desc
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public void setBankRspDesc(String bankRspDesc) {
		this.bankRspDesc = bankRspDesc == null ? null : bankRspDesc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.bank_transaction_id
	 * @return  the value of t_order.bank_transaction_id
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public String getBankTransactionId() {
		return bankTransactionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.bank_transaction_id
	 * @param bankTransactionId  the value for t_order.bank_transaction_id
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public void setBankTransactionId(String bankTransactionId) {
		this.bankTransactionId = bankTransactionId == null ? null : bankTransactionId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.notify_url
	 * @return  the value of t_order.notify_url
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public String getNotifyUrl() {
		return notifyUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.notify_url
	 * @param notifyUrl  the value for t_order.notify_url
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public void setNotifyUrl(String notifyUrl) {
		this.notifyUrl = notifyUrl == null ? null : notifyUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.payfor_notify_url
	 * @return  the value of t_order.payfor_notify_url
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public String getPayforNotifyUrl() {
		return payforNotifyUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.payfor_notify_url
	 * @param payforNotifyUrl  the value for t_order.payfor_notify_url
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public void setPayforNotifyUrl(String payforNotifyUrl) {
		this.payforNotifyUrl = payforNotifyUrl == null ? null : payforNotifyUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.callback_url
	 * @return  the value of t_order.callback_url
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public String getCallbackUrl() {
		return callbackUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.callback_url
	 * @param callbackUrl  the value for t_order.callback_url
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public void setCallbackUrl(String callbackUrl) {
		this.callbackUrl = callbackUrl == null ? null : callbackUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.notify_cnt
	 * @return  the value of t_order.notify_cnt
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public Integer getNotifyCnt() {
		return notifyCnt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.notify_cnt
	 * @param notifyCnt  the value for t_order.notify_cnt
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public void setNotifyCnt(Integer notifyCnt) {
		this.notifyCnt = notifyCnt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.notify_st
	 * @return  the value of t_order.notify_st
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public Integer getNotifySt() {
		return notifySt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.notify_st
	 * @param notifySt  the value for t_order.notify_st
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public void setNotifySt(Integer notifySt) {
		this.notifySt = notifySt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.open_id
	 * @return  the value of t_order.open_id
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public String getOpenId() {
		return openId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.open_id
	 * @param openId  the value for t_order.open_id
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public void setOpenId(String openId) {
		this.openId = openId == null ? null : openId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.extra
	 * @return  the value of t_order.extra
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public String getExtra() {
		return extra;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.extra
	 * @param extra  the value for t_order.extra
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public void setExtra(String extra) {
		this.extra = extra == null ? null : extra.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.country_id
	 * @return  the value of t_order.country_id
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public String getCountryId() {
		return countryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.country_id
	 * @param countryId  the value for t_order.country_id
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public void setCountryId(String countryId) {
		this.countryId = countryId == null ? null : countryId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.area_id
	 * @return  the value of t_order.area_id
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public String getAreaId() {
		return areaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.area_id
	 * @param areaId  the value for t_order.area_id
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public void setAreaId(String areaId) {
		this.areaId = areaId == null ? null : areaId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.region_id
	 * @return  the value of t_order.region_id
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public String getRegionId() {
		return regionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.region_id
	 * @param regionId  the value for t_order.region_id
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public void setRegionId(String regionId) {
		this.regionId = regionId == null ? null : regionId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.city_id
	 * @return  the value of t_order.city_id
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public String getCityId() {
		return cityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.city_id
	 * @param cityId  the value for t_order.city_id
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public void setCityId(String cityId) {
		this.cityId = cityId == null ? null : cityId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.county_id
	 * @return  the value of t_order.county_id
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public String getCountyId() {
		return countyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.county_id
	 * @param countyId  the value for t_order.county_id
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public void setCountyId(String countyId) {
		this.countyId = countyId == null ? null : countyId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.reserved3
	 * @return  the value of t_order.reserved3
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public Integer getReserved3() {
		return reserved3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.reserved3
	 * @param reserved3  the value for t_order.reserved3
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public void setReserved3(Integer reserved3) {
		this.reserved3 = reserved3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.reserved2
	 * @return  the value of t_order.reserved2
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public Integer getReserved2() {
		return reserved2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.reserved2
	 * @param reserved2  the value for t_order.reserved2
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public void setReserved2(Integer reserved2) {
		this.reserved2 = reserved2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.reserved1
	 * @return  the value of t_order.reserved1
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public Integer getReserved1() {
		return reserved1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.reserved1
	 * @param reserved1  the value for t_order.reserved1
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public void setReserved1(Integer reserved1) {
		this.reserved1 = reserved1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.modified
	 * @return  the value of t_order.modified
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public Date getModified() {
		return modified;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.modified
	 * @param modified  the value for t_order.modified
	 * @mbg.generated  Thu Oct 20 14:38:29 CST 2016
	 */
	public void setModified(Date modified) {
		this.modified = modified;
	}

	public String getSignature() {
		return signature;
	}

	public void setSignature(String signature) {
		this.signature = signature;
	}

	public String getMerchantId() {
		return merchantId;
	}

	public void setMerchantId(String merchantId) {
		this.merchantId = merchantId;
	}

	@Override
	public String toString() {
		return "Order [orderNo=" + orderNo + ", orderDt=" + orderDt
				+ ", source=" + source + ", orgId=" + orgId + ", orgOrderNo="
				+ orgOrderNo + ", account=" + account + ", appid=" + appid
				+ ", payChannelId=" + payChannelId + ", amount=" + amount
				+ ", settleAmt=" + settleAmt + ", clientIp=" + clientIp
				+ ", currency=" + currency + ", subject=" + subject + ", body="
				+ body + ", timeExpire=" + timeExpire + ", description="
				+ description + ", created=" + created + ", timePaid="
				+ timePaid + ", bankType=" + bankType + ", paySt=" + paySt
				+ ", refundSt=" + refundSt + ", refundedAmt=" + refundedAmt
				+ ", checkSt=" + checkSt + ", fee=" + fee + ", chnlFee="
				+ chnlFee + ", tranTp=" + tranTp + ", orderTp=" + orderTp
				+ ", settleSt=" + settleSt + ", rutId=" + rutId
				+ ", qrcodeUrl=" + qrcodeUrl + ", bankRspCd=" + bankRspCd
				+ ", bankRspDesc=" + bankRspDesc + ", bankTransactionId="
				+ bankTransactionId + ", notifyUrl=" + notifyUrl
				+ ", payforNotifyUrl=" + payforNotifyUrl + ", callbackUrl="
				+ callbackUrl + ", notifyCnt=" + notifyCnt + ", notifySt="
				+ notifySt + ", openId=" + openId + ", extra=" + extra
				+ ", countryId=" + countryId + ", areaId=" + areaId
				+ ", regionId=" + regionId + ", cityId=" + cityId
				+ ", countyId=" + countyId + ", reserved3=" + reserved3
				+ ", reserved2=" + reserved2 + ", reserved1=" + reserved1
				+ ", modified=" + modified + ", merchantId=" + merchantId
				+ ", signature=" + signature + "]";
	}
}